server:
  port: 8761

spring:
  application:
    name: discovery_service

eureka:
  client:
    register-with-eureka: false # ???? ??? ?? ??? client ? ????. ??? false
    fetch-registry: false
  server: #????? ????
    enable-self-preservation: false #????? ??, ??? ????? ?? ?? ??
    eviction-interval-timer-in-ms: 3000 #???? ????