server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///C:\Users\User\Desktop\could-config
          uri: https://github.com/WooJinDeve/spring-cloud-msa/cloud-config